### ISSUE TITLE
BGP MD5 authentication - Ideal if this is available (similar to the  spoke + transit external  device conn)

### ISSUE THREAD

**Issue by patelavtx** [terraform-aviatrix-modules/terraform-aviatrix-mc-edge#2]
+ Aviatrix 'external device connection' resource blocks have the BGP MD5 authentication available to use when establishing BGP peering

![image](https://user-images.githubusercontent.com/93542155/207396184-a4f28d61-c9f7-4683-ad18-bde7753d2949.png)

+ Great if this module (and underlying 'aviatrix_edge_spoke_external_device_conn' resource)  can have the BGP MD5 authentication option.

**Comment by Dennizz** [comment]
md5 is currently unsupported on this resource.
